# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMDBDemo' do

  pod 'FMDB', '~> 2.6.2'

  target 'FMDBDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FMDBDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
